spring.datasource.url=jdbc:postgresql://localhost:5432/sakura
spring.datasource.username=postgres
spring.datasource.password=S3f1r0t4
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=3000
jwt.secret=raOuoi03GyfU/IMaL8HR+FQ2avpuBNzTO43cmGHYa6A=
jwt.expiration-ms=86400000