spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.config.import=optional:file:.env[.properties]
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:3000}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
resend.api.key=${RESEND_API_KEY}
app.frontend-url=${FRONTEND_URL}

groq.api-key=${GROQ_KEY}
groq.model=llama3-8b-8192